### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by FabianRahm** [basz/SlmLocale#111]
At the moment, the module can't be installed while running PHP v8.0.0 or greater.

[InvalidArgumentException]                                                                                                     
  Package slm/locale at version 0.5.0 has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - slm/locale v0.5.0 requires php ^7.2 which does not match your installed version 8.0.20.     

Is there any plan to support newer PHP versions?

**Comment by svycka** [comment]
I am back to PHP for some time if I find time for this it is possible that we will support PHP 8 not sure how much changes it will need.

**Comment by kokspflanze** [comment]
i already prepared a little update, maybe you can check it 

https://github.com/basz/SlmLocale/pull/110

**Comment by demiankatz** [comment]
The need for PHP 8 support is becoming critical if this module is going to remain viable. Does @svycka or anyone else have time to look at #110, or is this project going to be retired? I'm willing to help if necessary; based on the fact that I'm using this module in PHP 8, I don't think there are major known problems -- it's just a question of composer.json being able to resolve.

**Comment by svycka** [comment]
I could merge it but first i want to fix CI. Replace travis with github
actions. Just can’t find time for this--
/*
  Pagarbiai S. Vytautas
*/

**Comment by demiankatz** [comment]
Thanks, @svycka! Do you happen to know if SlmLocale's Travis configuration is based on that of a different project? If so, it's possible that we can model a GitHub Actions configuration on the same project's current CI setup and save some time. I might be able to find some time to put something together and open a PR, but if there's an existing standard we're trying to align with, that will likely save me a lot of time in setting things up. :-)

**Comment by svycka** [comment]
Not sure, but for now running tests would be good enough for me--
/*
  Pagarbiai S. Vytautas
*/

**Comment by demiankatz** [comment]
@svycka, I believe that #112 should do the job for you. I hope this helps; please let me know if I can do more to assist you!
