### ISSUE TITLE
Unit testing applications using SlmLocale

### ISSUE THREAD

**Issue by intellix** [basz/SlmLocale#26]
I'm attempting to create unit tests for my application which makes use of SlmLocale UriPathStrategy and am having issues with testing controller dispatches like so:

``` php
public function testLoginActionCanBeAccessed()
{
    $this->dispatch('/en/account/login');
    $this->assertResponseStatusCode(200);
}
```

This returns 302 and when I dump the RequestURI within UriPathStrategy, I'm getting the following twice:

``` php
class Zend\Uri\Http#819 (10) {
  protected $validHostTypes => int(19)
  protected $user => NULL
  protected $password => NULL
  protected $scheme => string(4) "http"
  protected $userInfo =>  NULL
  protected $host => NULL
  protected $port => NULL
  protected $path => string(1) "/"
  protected $query => NULL
  protected $fragment => NULL
}
```

Whereas when I dump the RequestURI from a typical request via my browser:

``` php
object(Zend\Uri\Http)[210]
  protected 'validHostTypes' => int 19
  protected 'user' => null
  protected 'password' => null
  protected 'scheme' => string 'http' (length=4)
  protected 'userInfo' => null
  protected 'host' => string 'konoro.dev' (length=16)
  protected 'port' => null
  protected 'path' => string '/en/' (length=4)
  protected 'query' => string '' (length=0)
  protected 'fragment' => null
```

From what I've been reading in the code, it looks like the only time detection is done (and redirection) is onBootstrap of the Module. So the unit test defaults to / without a locale and every other dispatch uses the same requestUri and it needs to redirect to /en/ with them all.

Are you doing anything in particular when testing your stuff or does there need to be some change so the detection is done onDispatch() instead?

Thanks, Dom

**Comment by basz** [comment]
Hi, maintenance of this package has been taken over by me. If you still feel this issue is valid please go ahead and create a PR or contribute in any other manner. It's appreciated.

**Comment by koseduhemak** [comment]
Having the same issue. `UriPathStrategy` does not work with phpunit tests. Response code will be `302` no matter if you try with `/en/test` or `/test` and redirection is set to `/` as @intellix wrote.
So i wrote a little fix which disables the strategy for phpunit initiated requests completely unless someone has got a better idea.

Will issue pull request soon.
