### ISSUE TITLE
Don't redirect to default locale

### ISSUE THREAD

**Issue by glen-84** [basz/SlmLocale#41]
Is it possible to not redirect if the matched locale is the default?

For example, if the default locale is "en", stay at "/" instead of redirecting to "/en/".

Unless this is not recommended for some reason?

**Comment by ChipZ91** [comment]
Do you still want to add this feature? I know it's about 2 years old now, but I'm in that situation, too.

**Comment by kokspflanze** [comment]
@svycka i think can be closed now
