### ISSUE TITLE
UriPathStrategy set Router's baseurl

### ISSUE THREAD

**Issue by basz** [basz/SlmLocale#6]
Hello, I enjoyed working on the UriPathStrategy yesterday and the discussion is stirred.

I was thinking about the routing problems that I encountered yesterday when combining this module with AssetManager. 

Even though personally I would prefer pre-routing asset checking, SlmLocale's should not rely on such behavior - and the fact is the current implementation updated the baseurl of the router to have existing routes localized for every request. This may not be desired behavior. 

An application developer would like to have to define what exactly which routes are localized and which are not - the dynamic assets example is just one manifestation. Having paths of my project that aren't localized at all would be another...

So perhaps we should take this as a queue that there is some deeper problem with messing with the router the way SlmLocale/UriPathStrategy does.

Intuitively it feels to me that the UriPathStrategy can still be used as a detection meganism - but that - since SlmLocale is planned for ZF2 integration anyway - anything to do with localized routes should be handled by the router itself. That would then include the HostStrategy and perhaps other. 

Unfortunately I am too unfamiliar with the Router process to be authoritative here -but intuitively it feels to me that anything to do with routing should in fact be handled by the router. If that means that changes should be made to the the router a special route or plugin or whatever so be it. 

How to do this I leave up to smarter people :-)

thanks

**Comment by shinesoftware** [comment]
@basz have you solved in any way the asset manager issue? I have the same issue! :(

**Comment by basz** [comment]
@shinesoftware if ignoring the problem counts as 'solved' then yes :-p

**Comment by shinesoftware** [comment]
@basz so I have solved too :smiley:

**Comment by basz** [comment]
I don't think it can be solved and have accepted it as a limitation of how these particular modules work together.

**Comment by shinesoftware** [comment]
how have you solved the language router configuration? http://stackoverflow.com/questions/28498396/zf2-language-routes
