### ISSUE TITLE
Second strategy override first one when adding two identical strategies

### ISSUE THREAD

**Issue by jbenoit2011** [basz/SlmLocale#72]
In my case, I needed two `host` strategies. The `domain` could vary according to `locale`.
So I tried to set up, two `host` strategies with different parameters.
But when the strategies was added, the second one overlapped the first one. That's because strategy is pull from strategy plugin manager which gives you a reference to the object, not a new one.

**Comment by basz** [comment]
could you post (gist.github.com) your config please.

one solution that comes to mind is to set the 'shared' flag on the https://github.com/juriansluiman/SlmLocale/blob/master/src/SlmLocale/Strategy/StrategyPluginManager.php#L52 to false.

**Comment by jbenoit2011** [comment]
At first, I managed this by cloning strategies pulled from `StrategyPluginManager`. But your solution is far better since it uses the `ServiceManager` sharing feature.

So I overrode the `StrategyPluginManager::setInvokableClass` method:
```
    public function setInvokableClass($name, $invokableClass, $shared = null)
    {
        parent::setInvokableClass($name, $invokableClass, false);

        return $this;
    }
```

**Comment by jbenoit2011** [comment]
Your solution is the right one. I set `shareByDefault` to false(`protected $shareByDefault = false;`) in a custom strategy plugin manager inherited from `strategyPluginManager` and that works.
@juriansluiman Should we set this by default in `strategyPluginManager` since it does not break current tests?

**Comment by svycka** [comment]
@jbenoit2011 I think default behavior is correct you don't have to change this in `StrategyPluginManager` you can set this in your config `zend-servicemanager` documentation https://zendframework.github.io/zend-servicemanager/configuring-the-service-manager/#shared
