### ISSUE TITLE
ZF3 compatibility

### ISSUE THREAD

**Issue by Rockstar04** [basz/SlmLocale#74]
The ZF3 Service manager and Event manager are finally out.

The ServiceLocatorAwareInterface has been removed and it is currenlty used in [SlmLocale/Strategy/UriPathStrategy.php](https://github.com/juriansluiman/SlmLocale/blob/master/src/SlmLocale/Strategy/UriPathStrategy.php)

[Service Manager 3.0.0 Release Notes](https://github.com/zendframework/zend-servicemanager/releases/tag/release-3.0.0)

**Comment by sebfek** [comment]
+1

**Comment by tdutrion** [comment]
I am currently looking into it, there will also be a problem soon with the event aggregate: [EventManagerInterface::attachAggregate() and detachAggregate() removed](https://github.com/zendframework/zend-eventmanager/blob/develop/doc/book/migration/removed.md#eventmanagerinterfaceattachaggregate-and-detachaggregate) for file [Locale\Detector](https://github.com/juriansluiman/SlmLocale/blob/master/src/SlmLocale/Locale/Detector.php#L92)

**Comment by juriansluiman** [comment]
+1 Yeah we need to look into these things for zf3 compatibility.

**Comment by Rockstar04** [comment]
Just an update for this issue, ZF3 has officially been released: https://framework.zend.com/blog/2016-06-28-zend-framework-3.html

**Comment by flod1** [comment]
+1

**Comment by tdutrion** [comment]
I haven't be working on it for a while, but getting back on it at the moment (though I'll be at ForumPHP for two days and then organising ScotlandPHP on Saturday, so don't expect results soon :) )

**Comment by neo-rainboy** [comment]
@tdutrion @juriansluiman Can you guys provide me with a clue how to handle aggregate problem, that would be much appreciated ;)

**Comment by CreativeNative** [comment]
@tdutrion @juriansluiman no progress here? :-(

**Comment by svycka** [comment]
I have added ServiceManager and EventManager 3.0 support can you test it https://github.com/juriansluiman/SlmLocale/pull/77

**Comment by basz** [comment]
closing as this now is available in master.

ps. maintenance of this package has been taken over by me. If you still feel this issue is valid please go ahead and create a PR or contribute in an other manner.

**Comment by svycka** [comment]
@basz that's not really correct, we still don't support zend-mvc 3.0. Well I didn't added this because this would be BC break but if we will release 2.0 we can do it.

the fix should be simple I guess only namespace of zend-router changed eveything else should work but not tested yet

**Comment by basz** [comment]
ok, thanks for pointing this out, reopening

**Comment by basz** [comment]
Since we are stil below an 1.0.0 release I'm not to concerned about breaking changes between releases. These installs are not automatically updated by composer.

I'll tag 0.2.0 soon.

**Comment by svycka** [comment]
I din't noticed that we are still in 0.1 version :D I guess we can release 0.2

But I don't like that we have this install instruction in readme
```
{
    "require": {
        "slm/locale": ">=0.1.0,<1.2.0-dev"
    }
}
```
if someone used like this then we have BC break :( but it is 0.* releases maybe not a big problem? also if we will add correct composer dependencies this version will not be installed anyway.

**Comment by svycka** [comment]
also I would like to have version 1.0 since I use this in production (I don't like 0.x versions :D it's like stable but not really then what it is? I think better release 2.0.0... 5.0.0... 199.0.0 if needed but would be clear that it is stable. Unless we are under heavy development, but this is not the case)

so maybe instead of 0.2 we can have 1.0? what do you think @basz

**Comment by basz** [comment]
```
"slm/locale": ">=0.1.0,<1.2.0-dev"
```
that strange indeed. When you see something you don't like, open an issue or create a PR.

I don't forsee much refactoring besides the zf3-mvc and dropping php55 support. But that could be 2.0.0, so I'm ok with releasing a 1.0.0-beta1 as is...

**Comment by svycka** [comment]
I know.. just don't have much time at the moment, but I will try :D

**Comment by svycka** [comment]
ZF3 added in #95
