### ISSUE TITLE
Drop unsupported PHP versions

### ISSUE THREAD

**Issue by tdutrion** [basz/SlmLocale#76]
Hi!

After a while, I'm back on making this lib compatible with ZF3, and I was wondering if there would be anyone against dropping support for any unsupported php version (so > 5.6 only would be supported).

It make sense in a way as they are unsupported, and would allow using some of the new features (I personnaly love the `::class` syntax...)

**Comment by basz** [comment]
Hi, maintenance of this package has been taken over by me. If you still feel this issue is valid please go ahead and create a PR or contribute in an other manner.

**Comment by basz** [comment]
IMO 7.1+ only for next major version

**Comment by tdutrion** [comment]
Going with 7.1 means probably only ZF3+ and expressive, should we go ahead and drop all support for previous ZF versions as well?

**Comment by basz** [comment]
Well, it's easy for me. I'm not using this lib ATM. So I'll guess we should ask our contributors at the least... 

please vote thumbs up or down with a reaction on this comment
cc. @svycka @tdutrion @sasezaki @atukai @prolic @fwwarr @RWOverdijk @slavcodev @swiftchase @fwwarr @thomascrepain @coolmic

**Comment by prolic** [comment]
I don't use this lib anymore. But if you ask me, 7.1 only!

**Comment by svycka** [comment]
I am using php 7.1 and zend-mvc 2.7 with no problems. also, zend-mvc 3.0 support can be added very easy but not without BC break. But I guess we can do it. Unfortunately, I am only using this with zend-mvc 2.7 and don't have time now to work on this.

**Comment by svycka** [comment]
I have bumped php to `^5.6 | ^7.0` because we don't use any php 7.1 features I don't see the need to make it `^7.1`. Maybe if someone will find some time to refactor to use new php 7.1 features then yes we can do it later.
