### ISSUE TITLE
Breaks console usage

### ISSUE THREAD

**Issue by koseduhemak** [basz/SlmLocale#94]
Got fatal error if using console commands:
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SlmLocale\Strategy\UriPathStrategy::__construct() must be an instance of Zend\Mvc\Router\Http\TreeRouteStack or null, instance of Zend\Mvc\Router\Console\SimpleRouteStack given, called in ..../vendor/slm/locale/src/SlmLocale/Strategy/Factory/UriPathStrategyFactory.php on line 68 and defined in ..../vendor/slm/locale/src/SlmLocale/Strategy/UriPathStrategy.php:62`

Can we disable strategies depending on ConsoleRequest vs. normal HttpRequest? How to deal with it?

**Comment by koseduhemak** [comment]
I am on holiday till next week. Will test afterwards and report back.

**Comment by svycka** [comment]
I hope I fixed it in #95 but if not, please reopen
